name: Stream Video to YouTube

on:
  workflow_dispatch:  # Allow manual triggering
  push:  # Automatically run on push to the repository
    branches:
      - main

jobs:
  stream-video:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install FFmpeg and other dependencies
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y ffmpeg wget

    # Step 3: Create video links file (if not already in the repository)
    - name: Setup Video Links File
      run: |
        if [ ! -f video_links.txt ]; then
          echo "https://example.com/video1.mp4" > video_links.txt
          echo "https://example.com/video2.mp4" >> video_links.txt
        fi

    # Step 4: Run the streaming script
    - name: Run Streaming Script
      run: |
        python3 streaming_script.py
